[edgerouter]
TrinityFirst ansible_host=10.254.248.195
StJosephsDevizes ansible_host=10.254.248.178
StMarysCalne ansible_host=10.254.248.156
TheTrinitity ansible_host=10.254.248.199
Ludwell ansible_host=10.254.248.151


[edgerouter:vars]
ansible_connection=ssh
ansible_user=admin
ansible_password='Oakford658666'
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

